### ISSUE TITLE
Remove plugin from JetBrains plugins

### ISSUE THREAD

**Issue by Haehnchen** [xenji/phpstorm-symfony2-plugin#20]
I dont want to annoy you, but your plugin is not working since several PhpStorm releases #17. The `Symfony Plugin` handles views nicer.

getting several issue because of your plugin eg. https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/658.

**Comment by MECU** [comment]
I left a comment on the Repo Package as well: https://plugins.jetbrains.com/plugin/7057?pr=phpStorm

**Comment by MECU** [comment]
Response from email I sent:
> I've updated until-build of older plugin to make it unavailable when newer one can be installed.

**Comment by xenji** [comment]
Request is out to Jetbrains' plugin admin. I did not find any button to fully delete it. I've managed to remove all checkmarks for the respective compatibility. I hope this makes it invisible at least for the plugin manager.

**Comment by Haehnchen** [comment]
thx
